### ISSUE TITLE
How can I specify the folder name that the app will be install?

### ISSUE THREAD

**Issue by lipis** [atom/grunt-atom-shell-installer#116]
```
C:\Users\User\AppData\Local\foo
```

**Comment by anaisbetts** [comment]
@lipis It's the ID of your package.json usually

**Comment by lipis** [comment]
Fastest answer ever.. but it doesn't look that way.. :/ I'm trying to have an internal and production versions running side by side.. and nothing seems to update the `foo` part :)

**Comment by lipis** [comment]
or wait.. I had a dash (`-`) in the `name`.. but you mean `ID` as a property?! I don't have that at all..

**Comment by lipis** [comment]
It seems that way..if the `name` in package.json is  `foo-bar` the folder name is just `foo` :/

**Comment by anaisbetts** [comment]
Don't put a dash or dot in the name, Weird Stuff will happen
