### ISSUE TITLE
Creating delta packages (nuget)

### ISSUE THREAD

**Issue by mzmousa** [atom/grunt-atom-shell-installer#120]
When we set `remoteReleases` to the URL of our existing updates, how do we generate those updates? I am currently using this module to create my installers and getting a full nuget package, but not sure of how to make a delta nuget package.

**Comment by kevinmartin** [comment]
If you set `remoteReleases` to the url of the previous `RELEASES` file, you should get 3 new files (`*-full.nupkg`, `*-delta.nupkg`, and updated `RELEASES` file).

Upload those files to a static file server online and point the autoUpdater to the "folder" containing the files.

**Comment by mzmousa** [comment]
Does this mean I have to run my installer every time I want new full, Delta, and releases files?

**Comment by kevinmartin** [comment]
If by installer, you mean `grunt-electron-installer` then yes. If you mean the generated AppNameSetup.exe, no.

**Comment by kevinmartin** [comment]
There are samples apps out there that you can look through and see how they do this stuff.

**Comment by mzmousa** [comment]
I'm doing exactly as you said but I'm not getting a delta generated, only a new ```.exe``` and ```.nupkg``` :disappointed: could you link a sample app (preferably in nodejs) ? Right now I'm looking at ```Aluxian/Whatsie``` and was looking for any others to help me out

**Comment by mzmousa** [comment]
At first, delta packages wouldn't be be created if the version number was the same. Now they are produced when there is a different version number in my package.json. Thank you!

**Comment by mzmousa** [comment]
@KevinMartin would you know anything about [this](https://github.com/electron/grunt-electron-installer/issues/122) similar issue?
