### ISSUE TITLE
Handling Squirrel Events on Mac OS

### ISSUE THREAD

**Issue by shinbutchi** [atom/grunt-atom-shell-installer#126]
Hi everyone,
Does anybody know how to handle squirrel events on Mac OS. For example, I want to handle case --squirrel-install for auto startup electron application in the first time ?
Thanks.

**Comment by kevinsawicki** [comment]
> Does anybody know how to handle squirrel events on Mac OS. 

The `--squirrel-*` events are only fired on Windows.

> I want to handle case --squirrel-install for auto startup electron application in the first time ?

This information isn't available through an Electron API on macOS, you'd have to manage that yourself.
