### ISSUE TITLE
Setup.exe not working

### ISSUE THREAD

**Issue by Trixt0r** [atom/grunt-atom-shell-installer#17]
If I run the task, everything works fine. The *.nupkg, the RELEASES and the Setup.exe are generated.

But if I run Setup.exe, the gif pops up for some seconds and then disappears again. So, nothing actually happens.
If I run it from the console no output is generated.

This is the output while the task is running:

Running "create-windows-installer" task
Verifying property create-windows-installer.appDirectory exists in config...OK
Reading D:\test\node_modules\grunt-atom-shell-installer\vendor\Update.exe...OK
Writing D:\atom-shell\out\Release\Update.exe...OK
Reading D:\test\node_modules\grunt-atom-shell-installer\template.nuspec...OK
Writing C:\Users\trixt\AppData\Local\Temp\squirrel-installer-115226-712-rsrv7z\test.nuspec...OK

What am I doing wrong? I am running this on Windows 10 x64 Technical Preview and the newest Node JS version.

-Trixt0r

**Comment by sethlivingston** [comment]
+1

**Comment by xcoderzach** [comment]
I think I may have the same issue.  So mine DOES create `c:\Users\<user>\AppData\Local\<myapp>` but doesn't create any shortcuts in the start menu or desktop.

**Comment by paulcbetts** [comment]
@Trixt0r This means that your app is crashing on startup. 

> So mine DOES create c:\Users\<user>\AppData\Local\<myapp> but doesn't create any shortcuts in the start menu or desktop.

You need to create them yourself - see https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/squirrel-events.md and https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee#L230

**Comment by xcoderzach** [comment]
Thanks @paulcbetts, do you think this would be worth adding to atom-shell-starter?  I could add it in a pull request this weekend.  Or if not that, put it in the README.

**Comment by paulcbetts** [comment]
@xcoderzach Yes! I would take that PR for sure

**Comment by Trixt0r** [comment]
Well, creating the `C:\Users\<user>\AppData\Local\<myapp>` directory works now.

The problem is now, that, if I pack my app into `app.asar`, nothing happens. No Errors are thrown and atom shell quits. If replace the `app.asar` with my app folder, everything works just fine.

I am packing my app with `grunt-asar`.
I guess there are problems with resolving paths in the packaged form.
Maybe the package is corrupt... At least WinRAR is telling me that it is. I'll try to unpack it with the `asar` module itself.

Is there any possibility to run the task without having an `asar` file?
Or is the asar file necessary because of long filenames on Windows?


-Trixt0r

**Comment by paulcbetts** [comment]
@Trixt0r Can you file a separate bug?
