### ISSUE TITLE
Yontoo.C?

### ISSUE THREAD

**Issue by joshuawarner32** [atom/grunt-atom-shell-installer#4]
When I try to `npm install --save-dev grunt-atom-shell-installer`, my  Symantec virus scanner quarantines vendor/Setup.exe as containing "Yontoo.C".  See: http://www.symantec.com/security_response/writeup.jsp?docid=2014-040317-4040-99

* Is this a false detection?
* Did this sneak in somehow when this exe was last built?
* Is this actually part of / used by squirrel, and should we be concerned?

**Comment by paulcbetts** [comment]
This is definitely a false positive, can you report it? You can find the source to this binary at https://github.com/Squirrel/Squirrel.Windows/tree/master/src/Setup

**Comment by kevinsawicki** [comment]
Closing this out.
