### ISSUE TITLE
Allow different styles of signing parameters

### ISSUE THREAD

**Issue by joshuawarner32** [atom/grunt-atom-shell-installer#7]
I'd like to be able to sign with a key already installed on our build machine, which requires a different set of arguments than `certificateFile` and `certificatePassword` arguments can account for.

Any objections to adding a `signWithParams` argument that just gets passed through to squirrel?  Should I deprecate and/or remove `certificateFile` and `certificatePassword` at the same time?

The alternative for me would be adding `keystoreName` and `certificateName` arguments (corresponding to `/s` and `/n` arguments to `signtool.exe`, respectively).

Preferences?

**Comment by kevinsawicki** [comment]
> The alternative for me would be adding keystoreName and certificateName arguments

I kind of like this, seems straightforward and we wouldn't have to deprecate/remove the current signtool options.

**Comment by paulcbetts** [comment]
This would be fairly straightforward, this is actually already how Squirrel works. We could add the `signWithParams` parameter that trumps `certificate.*`

**Comment by joshuawarner32** [comment]
FWIW, I think `signWithParams` has the advantage of being as future-proof to new use-cases as we can possibly get.  I'll tentatively plan on making a PR adding a `signWithParams` argument, but without removing / deprecating the `certificateFile` and `certificatePassword` arguments.

**Comment by paulcbetts** [comment]
@joshuawarner32 :+1: :rabbit:
